import Head from "next/head"
import Image from "next/image"
import Footer from "../components/Footer"
import Navbar from "../components/Navbar"
import { PrismaClient } from "@prisma/client"

const { user } = new PrismaClient()

export default function Home({ initialUsers }) {
    console.log(initialUsers)
    return (
        <div className="overflow-hidden relative">
            <Head>
                <title>NextJS Playground</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <main className="relative">
                <section className="flex relative flex-col px-2 pt-8 mx-auto mt-10 mb-10 max-w-3xl text-center md:pt-13">
                    <span className="text-7xl font-black">
                        Solution for <br /> Startup Business
                    </span>
                    <span className="mt-10 text-2xl text-gray-500">
                        MonggiCorp Programming Services is an IT & web-based company that was established on 2020. All
                        our members have more than 5 years of experience in all related fields.
                    </span>
                </section>
                <section className="flex flex-col items-center px-2 pt-8 mx-auto mt-10 mb-10 max-w-3xl md:pt-13">
                    <span className="text-2xl font-black">Database</span>
                    <div className="w-full max-w-sm">
                        {initialUsers.map((item, index) => (
                            <div key={index} className="flex py-3 px-3 mt-3 rounded border">
                                <div className="p-6 rounded-full border"> </div>
                                <div className="ml-3">
                                    <div>{item.name}</div>
                                    <div>{item.email}</div>
                                </div>
                            </div>
                        ))}
                    </div>
                </section>
            </main>

            <Footer />
        </div>
    )
}

export async function getServerSideProps() {
    const users = await user.findMany()

    return {
        props: {
            initialUsers: users,
        },
    }
}
