/* eslint-disable @next/next/no-img-element */
import Head from "next/head"
import Image from "next/image"
import Footer from "../components/Footer"
import Navbar from "../components/Navbar"
import { PrismaClient } from "@prisma/client"
import { useEffect, useState } from "react"
import Particles from "react-particles-js"
const { user } = new PrismaClient()

export default function Home({ initialUsers }) {
    console.log(initialUsers)
    const [isDark, setIsDark] = useState(false)

    const toggleDarkMode = (params) => {
        if (isDark) {
            document.documentElement.classList.add("dark")
            setIsDark(!isDark)
        } else {
            document.documentElement.classList.remove("dark")
            setIsDark(!isDark)
        }
    }

    return (
        <div className="overflow-hidden relative transition duration-500 ease-in-out dark:text-white dark:bg-gray-900">
            <Head>
                <title>NextJS Playground</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <section className="fixed inset-0 w-screen h-screen shooting-stars">
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
                <span className="bg-yellow-500 star dark:bg-white"></span>
            </section> */}

            <Navbar />

            <main className="relative">
                <section className="flex justify-center px-2 pt-10 mx-auto mt-10 mb-10 text-center md:pt-13">
                    <Particles
                        className="absolute top-0 left-0 z-0 w-screen h-[60vh]"
                        params={{
                            particles: {
                                number: {
                                    value: 50,
                                },
                                size: {
                                    value: 3,
                                },
                                color: "#CC582B",
                                links: {
                                    color: "#CC582B",
                                },
                            },
                            interactivity: {
                                events: {
                                    onhover: {
                                        enable: true,
                                        mode: "repulse",
                                    },
                                },
                            },
                        }}
                    />
                    <div className="flex relative flex-col items-center max-w-3xl">
                        <span className="text-4xl font-black md:text-7xl">
                            Software Solutions. <br /> Startup Business
                        </span>
                        <span className="mt-10 text-lg text-gray-500">
                            MonggiCorp Programming Services is an IT & web-based company that was established on 2020.
                            All our members have more than 5 years of experience in all related fields.
                        </span>
                        <div
                            onClick={toggleDarkMode}
                            className="flex justify-center content-center items-center py-3 px-10 mx-2 mt-10 text-lg font-black text-white bg-orange-600 rounded border transition ease-in-out delay-100 cursor-pointer hover:bg-white hover:text-yellow-800"
                        >
                            Get started
                        </div>
                    </div>
                </section>
                <section className="flex justify-center px-2 pt-16 pb-14 mx-auto mt-10 mb-10 text-center md:pt-13 0">
                    <div className="flex relative flex-col items-center max-w-3xl">
                        <span className="text-xl">What we use on our projects.</span>
                        <div className="flex flex-wrap justify-center mt-3">
                            <img
                                src="assets/logo/gatsby.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                            <img
                                src="assets/logo/javascript.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                            {/* <img
                                src="assets/logo/next-js-circle.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale hover:grayscale-0"
                            /> */}
                            <img
                                src="assets/logo/next-js.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                            <img
                                src="assets/logo/nodejs.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                            <img
                                src="assets/logo/npm.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                            <img
                                src="assets/logo/react-spring.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-28 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                            <img
                                src="assets/logo/redux.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                            <img
                                src="assets/logo/react.svg"
                                alt="saddddd"
                                className="my-3 mx-5 h-16 transition duration-500 ease-in-out cursor-pointer filter grayscale contrast-200 hover:grayscale-0"
                            />
                        </div>
                    </div>
                </section>
                <section className="flex flex-col items-center px-2 pt-8 mx-auto mt-10 mb-10 max-w-3xl md:pt-13">
                    <span className="text-2xl font-black">Database</span>
                    <div className="w-full max-w-sm">
                        {initialUsers.map((item, index) => (
                            <div key={index} className="flex py-3 px-3 mt-3 rounded border">
                                <div className="p-6 rounded-full border"> </div>
                                <div className="ml-3">
                                    <div>{item.name}</div>
                                    <div>{item.email}</div>
                                </div>
                            </div>
                        ))}
                    </div>
                </section>
            </main>

            <Footer />
        </div>
    )
}

export async function getServerSideProps() {
    const users = await user.findMany()

    return {
        props: {
            initialUsers: users,
        },
    }
}
